#!/usr/bin/env bash
set -euo pipefail

cmd=${1:-}

case "$cmd" in
  rebuild|*)
  (
    # Build PDFs from TeX
    pdflatex -interaction=nonstopmode The_Living_Way.tex >/dev/null 2>&1 || exit 1
    pdflatex -interaction=nonstopmode The_Living_Suttas.tex >/dev/null 2>&1 || exit 1
	    # Regenerate HTML from TeX using pandoc
	    pandoc -s --from=latex --to=html The_Living_Way.tex -o The_Living_Way.html
	    pandoc -s --from=latex --to=html The_Living_Suttas.tex -o The_Living_Suttas.html
  ) &
    ;;
esac
